// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectServer(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ConnectServer'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetDevEnvironment() {
  return window['go']['main']['App']['GetDevEnvironment']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
