// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelExecution() {
  return window['go']['main']['App']['CancelExecution']();
}

export function ConnectServer(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['ConnectServer'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function FetchDictionary(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FetchDictionary'](arg1, arg2, arg3, arg4);
}

export function GetAppConfig() {
  return window['go']['main']['App']['GetAppConfig']();
}

export function GetDevEnvironment() {
  return window['go']['main']['App']['GetDevEnvironment']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SelectDataFile() {
  return window['go']['main']['App']['SelectDataFile']();
}

export function SelectSPSSBinary() {
  return window['go']['main']['App']['SelectSPSSBinary']();
}
